version: "3.9"

services:
  # -------------------------------------
  # POSTGRES SERVICES
  # -------------------------------------
  postgres_auth:
    image: postgres:16
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: swift
      POSTGRES_PASSWORD: swift
      POSTGRES_DB: auth_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U swift -d auth_db"]
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
      - "5433:5432"
    volumes:
      - pg_auth_data:/var/lib/postgresql/data

  postgres_chat:
    image: postgres:16
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: swift
      POSTGRES_PASSWORD: swift
      POSTGRES_DB: chat_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U swift -d chat_db"]
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
      - "5434:5432"
    volumes:
      - pg_chat_data:/var/lib/postgresql/data

  postgres_task:
    image: postgres:16
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: swift
      POSTGRES_PASSWORD: swift
      POSTGRES_DB: task_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U swift -d task_db"]
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
      - "5435:5432"
    volumes:
      - pg_task_data:/var/lib/postgresql/data
    
  postgres_cloud:
    image: postgres:16
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: swift
      POSTGRES_PASSWORD: swift
      POSTGRES_DB: cloud_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U swift -d cloud_db"]
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
      - "5436:5432"
    volumes:
      - pg_cloud_data:/var/lib/postgresql/data

  # -------------------------------------
  # REDIS
  # -------------------------------------
  redis_chat:
    image: redis:7-alpine
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
      - "6380:6379"
    volumes:
      - redis_chat_data:/data

  # -------------------------------------
  # ZOOKEEPER + KAFKA
  # -------------------------------------
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    healthcheck:
      test: ["CMD", "echo", "ruok", "|", "nc", "localhost", "2181"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      zookeeper:
        condition: service_healthy
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server kafka:9092 --list >/dev/null 2>&1"]
      interval: 10s
      timeout: 5s
      retries: 10
    ports:
      - "9092:9092"

  # -------------------------------------
  # AUTH SERVICE
  # -------------------------------------
  auth_service:
    build:
      context: .
      args:
        SERVICE: auth
    depends_on:
      postgres_auth:
        condition: service_healthy
      kafka:
        condition: service_healthy
    env_file:
      - .env
    environment:
      AUTH_SERVER_PORT: ${AUTH_SERVER_PORT}
      DB_AUTH_CONNECTION_STRING: ${DB_AUTH_CONNECTION_STRING}
      KAFKA_ADDRESS: ${KAFKA_ADDRESS}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "${AUTH_SERVER_PORT}:${AUTH_SERVER_PORT}"

  # -------------------------------------
  # CHAT SERVICE
  # -------------------------------------
  chat_service:
    build:
      context: .
      args:
        SERVICE: chat
    depends_on:
      postgres_chat:
        condition: service_healthy
      redis_chat:
        condition: service_healthy
      kafka:
        condition: service_healthy
    env_file:
      - .env
    environment:
      CHAT_SERVER_PORT: ${CHAT_SERVER_PORT}
      DB_CHAT_CONNECTION_STRING: ${DB_CHAT_CONNECTION_STRING}
      CHAT_REDIS_CONNECTION_STRING: ${CHAT_REDIS_CONNECTION_STRING}
      USERS_STORAGE: ${USERS_STORAGE}
      GROUPS_STORAGE: ${GROUPS_STORAGE}
      CHATS_STORAGE: ${CHATS_STORAGE}
      KAFKA_ADDRESS: ${KAFKA_ADDRESS}
    volumes:
      - ./storage:/storage
    ports:
      - "${CHAT_SERVER_PORT}:${CHAT_SERVER_PORT}"

  # -------------------------------------
  # TASK SERVICE
  # -------------------------------------
  task_service:
    build:
      context: .
      args:
        SERVICE: task_tracker
    depends_on:
      postgres_task:
        condition: service_healthy
      kafka:
        condition: service_healthy
    env_file:
      - .env
    environment:
      TASK_SERVER_PORT: ${TASK_SERVER_PORT}
      DB_TASK_CONNECTION_STRING: ${DB_TASK_CONNECTION_STRING}
      KAFKA_ADDRESS: ${KAFKA_ADDRESS}
    ports:
      - "${TASK_SERVER_PORT}:${TASK_SERVER_PORT}"
  
  cloud_service:
    build:
      context: .
      args:
        SERVICE: cloud
    depends_on:
      postgres_cloud:
        condition: service_healthy
      kafka:
        condition: service_healthy
    env_file:
      - .env
    environment:
      TASK_SERVER_PORT: ${CLOUD_SERVER_PORT}
      DB_TASK_CONNECTION_STRING: ${DB_CLOUD_CONNECTION_STRING}
      KAFKA_ADDRESS: ${KAFKA_ADDRESS}
    ports:
      - "${CLOUD_SERVER_PORT}:${CLOUD_SERVER_PORT}"

volumes:
  pg_auth_data:
  pg_chat_data:
  pg_task_data:
  pg_cloud_data:
  redis_chat_data:
